// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "Metadata": {
    "title": "Al Hatab",
    "description": "We must choose our daily food carefully, which is why Al-Hatab Bakeries offers you fresh baked goods - from traditional local bread to baguettes, burger buns, tortillas, and soft toast - to make your daily meals more enjoyable. If you prefer low-calorie products, ask about our special selection of reduced-calorie bread."
  },

  "Header": {
    "chalnge-language": "Chalnge Language"
  },

  "Lists": {
    "columns": {
      "name": "Name",
      "price": "Price",
      "image": "Image"
    },
    "List_1": {
      "title": "Bakery",
      "item_1": {
        "name": "Tannour Bread",
        "price": "5"
      },
      "item_2": {
        "name": "Regular Arabic Bread",
        "price": "1"
      },
      "item_3": {
        "name": "Arabic Brown Bread",
        "price": "2"
      },
      "item_4": {
        "name": "Tortilla Bread",
        "price": "4"
      },
      "item_5": {
        "name": "Burger Bun",
        "price": "10"
      },
      "item_6": {
        "name": "Toast",
        "price": "4"
      }
    },
    "List_2": {
      "title": "Salads",
      "item_1": {
        "name": "Fattoush Salad",
        "price": "12"
      },
      "item_2": {
        "name": "Caesar Salad",
        "price": "17"
      },
      "item_3": {
        "name": "Feta Cheese Salad",
        "price": "11"
      }
    },
    "List_3": {
      "title": "Groceries",
      "item_1": {
        "name": "Al-Jouf Olive Oil",
        "price": "14"
      },
      "item_2": {
        "name": "Soft Drinks",
        "price": "2.5"
      },
      "item_3": {
        "name": "Juices",
        "price": "7"
      },
      "item_4": {
        "name": "Water",
        "price": "1"
      }
    },
    "List_4": {
      "title": "Saudi Desserts",
      "item_1": {
        "name": "Kleija",
        "price": "2 SAR per piece - 20",
        "description": "per box (11 pieces)"
      },
      "item_2": {
        "name": "Basbousa",
        "price": "4"
      },
      "item_3": {
        "name": "Hanini",
        "price": "7"
      }
    }
  }
};
export default messages;